# https://www.notion.so/bizforward/6d3e82b63d4b431e8949d257a5f3f5e9?pvs=4#ec1c35e0a2fb48e49e39f70cec87474e",
# Feature_Xは0-originではなく1-origin",
feature_list = [
    "Feature_10",
    "Feature_14",
    "Feature_15",
    "Feature_17",
    "Feature_26",
    "Feature_31",
    "Feature_35",
    "Feature_45",
    "Feature_46",
    "Feature_47",
    "monthly_min_balance",
    "monthly_q25_balance",
    "monthly_max_balance",
    "monthly_q25_diff_balance",
    "all_q25_balance",
    "all_q50_balance",
    "all_max_sub_min_diff_balance",
    "all_size_in_a_month_mean",
    "all_size_in_a_month_25%",
    "all_size_in_a_month_75%",
    "Feature_14_DivLeadDesiredAmount",
    "Feature_15_DivLeadDesiredAmount",
    "Feature_31_DivLeadDesiredAmount",
    "Feature_45_DivLeadDesiredAmount",
    "Feature_46_DivLeadDesiredAmount",
    "monthly_min_balance_DivLeadDesiredAmount",
    "monthly_q25_balance_DivLeadDesiredAmount",
    "monthly_q50_balance_DivLeadDesiredAmount",
    "monthly_q50_diff_balance_DivLeadDesiredAmount",
    "all_q25_balance_DivLeadDesiredAmount",
    "all_q50_balance_DivLeadDesiredAmount",
]
