name: CI Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource:
          - name: lambda/get_anakin_score
            path: aws/lambda/get_anakin_score
          - name: lambda/get_vader_score
            path: aws/lambda/get_vader_score
          - name: lambda/get_obiwan_score
            path: aws/lambda/get_obiwan_score
          - name: lambda/get_luke_score
            path: aws/lambda/get_luke_score
          - name: databricks
            path: databricks

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies for ${{ matrix.resource.name }}
        run: |
          cd ${{ matrix.resource.path }}
          if [ -f pyproject.toml ]; then
            pip install -e '.[dev]'
          else
            echo "No pyproject.toml found in ${{ matrix.resource.path }}"
          fi

      - name: Lint Code in ${{ matrix.resource.path }}
        run: |
          cd ${{ matrix.resource.path }}
          pflake8

      - name: Run Tests for ${{ matrix.resource.name }}
        run: |
          cd ${{ matrix.resource.path }}
          if [ -d "./tests" ]; then
            python -m pytest ./tests
          else
            echo "No tests directory found in ${{ matrix.resource.path }}; skipping tests."
          fi
